### ISSUE TITLE
server crash on sending message to blocked user

### ISSUE THREAD

**Issue by 0wx** [grammyjs/grammY#171]
How do I ignore if the user block the bot while there's still pending update? Tried `bot.errorHandler` but it's still crash the server if the user block the bot

**Comment by KnorpelSenf** [comment]
You should always `await` all async operations. Then your errors will be caught by grammY and `bot.catch`/`bot.errorHandler` will be able to catch them.

If you think you're already doing this but there's still an uncaught error, you should share the logs.

If you're using `async`/`await` correctly, you can also wrap the calls in try-catch statements to catch potential errors.

**Comment by 0wx** [comment]
@KnorpelSenf it's make my server so slow tho, but at least it doesn't crash anymore, thanks!

**Comment by HeeroML** [comment]
It shouldn't slow down the server, check your calls to databases, etc

**Comment by KnorpelSenf** [comment]
The use of `async`/`await` per se is usually not degrading performance measurably.

It may be the case that your server slows down because you're using the simple built-in polling which processes updates sequentially in order to be predictable. If you would like to make use of fully concurrent update processing (while still catching errors) you should check out grammY runner.
