### ISSUE TITLE
Bot context without interaction

### ISSUE THREAD

**Issue by laosb** [grammyjs/grammY#186]
Currently it seems that context can be only obtained from an user interaction with the bot; However, there're plenty of cases where a specific context of a certain chat is needed. For example, the bot may offer notification subscription, and when the thing happened, the bot may need to notify the user based on the user's language settings (which can be queried in context).

I understand that the current bot context implementation is designed with a specific Bot API update in mind. My proposal is to provide a way to save a specific Bot API update, and allow recreating the context  and using it afterwards. Is that currently doable?

**Comment by KnorpelSenf** [comment]
Yes, this is very much doable. In order to create a context object, you'll need:
1. The update object, which you can obtain from a previous context object via `ctx.update`
2. An Api object which you can simply create via `new Api()`
3. The bot's information which is available after initialisation via `bot.botInfo`

The API reference of grammY which is linked in the README may help you.

However, there's not much of a reason to actually create context objects. All they do is to give you data from and update object, and provide shortcuts to the API calls. If you already have an update object, you might just as well use `bot.api`. This is an instance of `Api` and it gives you complete access to the Bot API without any context object.

**Comment by KnorpelSenf** [comment]
I see.

The context object is modified continuously while it's passed through the middleware tree. Plugins register and unregister properties and functions and API transformers (which can actually be closures) and so on. There's no way to persist this data in a database. All you can do is literally to store the context object in RAM in a `Map` or something. I'm not sure if this has any side-effects for some plugin or so, I don't know enough of the ecosystem by heart to say if any of the authors assumed context objects to be short-lived.

Most libraries do export the raw functions which they use internally. You can import things statically from them and supply the necessary values.

A lot of the convenience in the libraries comes from the fact that we have update objects, so we know what user the bot is talking to etc. Take that away, and you'll be left with the actual complexity of the problem, the one which the plugins try to hide. I'm afraid there isn't an easy solution to this, as it's not so much something we could implement in the library.
