### ISSUE TITLE
 webhook callback: token paramenter?

### ISSUE THREAD

**Issue by devnbp** [grammyjs/grammY#217]
my application handles a lot of bots, but why grammY have no ability to handle updates of different access tokens using only one bot instance? how can I do something like that:
```js
webhookCallback(bot, 'express')(req, res, token);
```

**Comment by KnorpelSenf** [comment]
You just need to create your bot for every request, something like

```ts
const composer = new Comopser()
composer.on("message", ctx => ctx.reply("Hi"))

app.use("/:token", (res, req) => {
  const bot = new Bot(req.params.token)
  bot.use(composer)
  return webhookCallback(bot, "express")(req, res)
})
```
(Untested, coded on GitHub.)

Note that this will have to initialise the bot for every request because the bot information must be fetched every time. If you have it cached somewhere, you can inject it into the constructor in order to prevent the init call to `getMe`.

**Comment by devnbp** [comment]
oh thanks, it looks like I didn't read the documentation fully, now I can clearly see how to solve my problem
