### ISSUE TITLE
[Feature request]: Unite `.command()` and `.callbackQuery()` for Composer

### ISSUE THREAD

**Issue by LWJerri** [grammyjs/grammY#220]
Hello. Please, add support `.command().callbackQuery()`, because it's not work now.

What we have now:
```ts
async function startCommand(ctx: CustomContext) {
  await ctx.reply("Hello!");
}

composer.command("start", async (ctx) => await startCommand(ctx));
composer.callbackQuery("start", async (ctx) => await startCommand(ctx));
```

What I wanna get:
```ts
composer.callbackQuery("start").command("start", async (ctx) => await ctx.reply("Hello!"));
```
- When I write this code I didn't get any response or error from the command or callback.

**Comment by roj1512** [comment]
How have you understood `callbackQuery`?

**Comment by KnorpelSenf** [comment]
If you chain method calls, they will be concatenated by AND. Here are the docs: https://grammy.dev/guide/filter-queries.html#combine-with-and

What you're doing by putting everything on one line is to filter for updates that are both commands and callback queries at the same time. This does not exist. If you send a command, it will not be a callback query (obviously) and vice-versa. That's why you don't get any resopnse.

**Comment by LWJerri** [comment]
> If you chain method calls, they will be concatenated by AND. Here are the docs: https://grammy.dev/guide/filter-queries.html#combine-with-and
> 
> What you're doing by putting everything on one line is to filter for updates that are both commands and callback queries at the same time. This does not exist. If you send a command, it will not be a callback query (obviously) and vice-versa. That's why you don't get any resopnse.

Hello. Yeah, I understand it, but I forgot the queries filter. Thanks!
