### ISSUE TITLE
feat: Add missing properties on some types

### ISSUE THREAD

**Issue by henriquesgi** [grammyjs/grammY#260]
Hello.

Some properties are missing from some types, like the type `ChatFromGetChat`.

Check it out:
1. try to get chat permissions using events:

```ts
bot.on(":new_chat_members:me", async (ctx) => {
  const { permissions } = await ctx.getChat();
  //
});
```

2. You got: `Property 'permissions' does not exist on type 'ChatFromGetChat'`

**Comment by dcdunkan** [comment]
Hi! The types aren't missing any properties. 

> Property 'permissions' does not exist on type 'ChatFromGetChat'

^ And this is not just what TypeScript is saying. TypeScript says,

> Property 'permissions' does not exist on type 'ChatFromGetChat'.
> **Property 'permissions' does not exist on type 'PrivateGetChat'**.

Where `ChatFromGetChat` is,

```ts
export type ChatFromGetChat =
  | Chat.PrivateGetChat
  | Chat.GroupGetChat
  | Chat.SupergroupGetChat
  | Chat.ChannelGetChat;
```

So it is because the filter query `:new_chat_members:me` only filter the update type and not really the chat type. So, when you call `ctx.getChat()` it returns `ChatFromGetChat` type, which can be the information about any type of chats: private, group, supergroup or channel chats.

And as you know the property `permissions` is only for groups and supergroups. So, to access the permissions property, you need to filter the chat type by yourself.

```ts
bot.on(":new_chat_members:me", async (ctx) => {
  const chat = await ctx.getChat();
  if (chat.type == "group" || chat.type == "supergroup") {
    console.log(chat.permissions); // No type errors.
  }
});
```

But generally, since Telegram Bot API documentation says

> new_chat_members: New members that were added to the **group or supergroup** and information about them (the bot itself may be one of these members).

that, the `new_chat_member` update is only for groups and supergroups, I think it is safe to assert types for the returned value.

```ts
// Node
import { Chat } from "grammy/types";
// Deno
import { Chat } from "https://deno.land/x/grammy@v1.10.1/types.ts";

bot.on(":new_chat_members:me", async (ctx) => {
  const { permissions } = await ctx.getChat() as Chat.MultiUserGetChat;
  console.log(permissions); // No type errors.
});
```

Hope this helps!

**Comment by KnorpelSenf** [comment]
This looks solved, so I will close this issue. Feel free to comment or reopen if there are more questions.
