### ISSUE TITLE
Context is type of never when using chatType filter on poll_answer

### ISSUE THREAD

**Issue by ExposedCat** [grammyjs/grammY#280]
```javascript
import { Composer } from 'grammy'
const controller = new Composer<CustomContext>()
```
`ctx` type is `never`:
```javascript
controller
	.chatType(['supergroup', 'group'])
	.on('poll_answer', async ctx => {
		// ctx type is never
	})
```
`ctx` type is correct:
```javascript
controller
	.on('poll_answer', async ctx => {
		// ctx type is correct
	})
```
However, there is no such issue with (at least some) other update types

**Comment by KnorpelSenf** [comment]
This behaviour is correct.

The point of `bot.chatType` is to make sure that only those updates are matching which are known to originate from the specified chat type(s). However, there's no way to determine the chat type for `poll_answer` updates (which makes a lot of sense because polls can be sent to many different chats, yet they all share the same state). Consequently, poll_answer updates can never match `bot.chatType`. This is captured by the type system which tells you that such a context object can `never` exist. Thus, the code snippet above is correct.

**Comment by ExposedCat** [comment]
There is no `chat` field on update, so we can't ensure what type of chat it is.
