### ISSUE TITLE
feat: grammy/web builds for all plugins and storage adapters 

### ISSUE THREAD

**Issue by dandaka** [grammyjs/grammY#372]
**Now**

All Storage Adapters (and Session as it is dependent on them) do not support working without Node API. So Grammy can't be used with the sessions plugin on Cloudflare Workers (and similar Edge platforms).

**Expected**

Some/all Storage Adapters can be imported without Node API dependency.

**Comment by KnorpelSenf** [comment]
This is generally the case with all plugins. The core repository is the only project that has a web build. We need to add a similar setup to all ~30 repos. Contributions are very welcome!

**Comment by dandaka** [comment]
@KnorpelSenf did you have any branch, where you implemented the feature for the core rep?

**Comment by KnorpelSenf** [comment]
grammY is naively written for Deno. Deno code is compatible with the browser and cloudflare. That's why a simple `deno bundle` pass to remove the type annotations already gave us a web build that could run in the browser and in cloudflare.

The only problem used to be that cloudflare didn't support top-level await. (This was added by now.) This is why we sort of always had web builds, so it wasn't really an isolated feature we added at some point.

The tooling to create these JavaScript bundles has evolved over time. I think the most useful PQ to check is #339 which takes the existing web bundle and adds it to the npm package in order for it to be consumed by wrangler.

**Comment by KnorpelSenf** [comment]
@dandaka are you interested in working on this? I'd be happy to review and assist. I'm sure @roziscoding will also be able to answer any questions :)

**Comment by dandaka** [comment]
I am a junior dev at best, learning React + Typescript + Node + modern JS at the same time while developing a pet project. So while I am interested, it might take a gigantic effort at my current level :)

**Comment by KnorpelSenf** [comment]
Ah I'm not worried about that. grammY is the right place to achieve great things no matter what your level of expertise is. There are many stories to tell of novice coders who grew far beyond themselves here, so if you'd like to give it a try, I'm fairly certain that you'll succeed :)

**Comment by PonomareVlad** [comment]
I encountered a similar problem when deploying on [Vercel Edge Runtime](https://vercel.com/docs/concepts/functions/edge-functions/edge-runtime).

If importing the grammY core for web [is not a problem](https://github.com/PonomareVlad/grammYVercelEdge/blob/af34e194a056f7a71edeca558185c7aa0fd67001/src/bot.mjs#LL1C1-L1C1):

```js
import { Bot } from "grammy/web"; // instead of "grammy"
```

The plugins will [still use the default import](https://github.com/grammyjs/storages/blob/5308a6f7540de26990515f0b86045ed83357d6d2/packages/mongodb/src/deps.node.ts#L2):

```js
import { /*...*/ } from "grammy";
```

To solve this problem, I tried two methods:

1. [Using an override package](https://github.com/PonomareVlad/WebgrammY) that re-exports the default `grammy` export from the `grammy/web` path.
2. Using [custom build](https://github.com/grammyjs/grammY/compare/main...PonomareVlad:grammY:web#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L35-L42) of grammY package with default web export.

The first option seems to be the most compatible, but it have an issue with TypeScript types import.

At the moment, I have not found a way to fix this, and I do not have lot experience with TypeScript.

As a result, for my projects, I decided to use the second method, in which the types imports correctly and all plugins that do not depend on built-in Node.js modules too.

[Working example](https://github.com/PonomareVlad/TelegrAIChatBot) 🙂

**Comment by dandaka** [comment]
I have moved to Deno + Deno Deploy and never looked back!

**Comment by KnorpelSenf** [comment]
Well that's certainly the smart choice, but people will still need `/web` exports of all packages, so this issue is still relevant

**Comment by PonomareVlad** [comment]
@KnorpelSenf Can you explain or give instructions on how it would be correct to implement `web` exports in plugins ?

**Comment by roziscoding** [comment]
I believe it'd be something similar to [what's done for the core package](https://github.com/grammyjs/grammY/blob/main/bundling/bundle-web.ts)

**Comment by KnorpelSenf** [comment]
Ideally, the solution looks like this:

1. create a new repo with shared build scripts for all other repos
2. migrate to dnt
3. take over and adjust the bundling script from this repo
4. use the shared build script in deno tasks in all repos

I am not sure when to tackle this, but I find it hard to imagine that this is possible without step 2 because d2n requires a config file, and this config file is different per project. Unless we find an easy way to solve this (long CLI flags?), we need to move to a tool that requires no config.

**Comment by wojpawlik** [comment]
Overkill. Other packages already can `deno run https://raw.githubusercontent.com/grammyjs/grammY/main/bundling/bundle-web.ts`.

> The plugins will [still use the default import](https://github.com/grammyjs/storages/blob/5308a6f7540de26990515f0b86045ed83357d6d2/packages/mongodb/src/deps.node.ts#L2):

Good point @PonomareVlad. Entry point could provide `"node"` and `"default"` [consitional exports](https://nodejs.org/api/packages.html#conditional-exports). This would obsolete `"grammyjs/web"`.

**Comment by KnorpelSenf** [comment]
> This would obsolete `"grammyjs/web"`.

I like that a lot. Can I ask you to procrastinate a little more and open a PQ?

**Comment by KnorpelSenf** [comment]
Closing in favour of #559
