### ISSUE TITLE
`node-fetch` dependency breaks grammY API calls in minified builds

### ISSUE THREAD

**Issue by winstxnhdw** [grammyjs/grammY#409]
Specifically, this part of `node-fetch`. Minified builds are important for improving cold-start time and performance in serverless platforms. I am aware that a port to fetch will be coming in v2.0. This is just a PSA for those working with grammY and serverless.

![image](https://user-images.githubusercontent.com/56998716/233860560-94c552a3-f298-445d-99c8-933ad3fb0c06.png)

**Comment by KnorpelSenf** [comment]
This is only relevant if one wants to minify the build that is created explicitly for Node.js. All other builds do not have this problem, such as the web build which can be used on CFW.

**Comment by winstxnhdw** [comment]
@KnorpelSenf I am unable to build for CFW with a minimal example.

**Comment by KnorpelSenf** [comment]
You should install grammY from npm and then import it from the subpath `grammy/web` which is Node-free.

**Comment by KnorpelSenf** [comment]
Are you asking this question before or after reading https://grammy.dev/hosting/cloudflare-workers.html?

**Comment by winstxnhdw** [comment]
You are right. I have not read that. Let me fix this.

**Comment by KnorpelSenf** [comment]
I'm curious—what would be the use case to minify the build and then run it using Node? I thought the main reason to minify JS is to deliver it to the browser, but this is already done using the web build or a different Deno build.

**Comment by winstxnhdw** [comment]
> I'm curious—what would be the use case to minify the build and then run it using Node? I thought the main reason to minify JS is to deliver it to the browser, but this is already done using the web build or a different Deno build.

I think this [article](https://medium.com/capital-one-tech/applying-minification-and-uglification-to-aws-lambda-functions-dbc7ad75241) has put it nicely.

**Comment by KnorpelSenf** [comment]
I see. So to sum it up, instead of using a service with 0 ms cold start time, you want to use a service that has a couple of hundred milliseconds cold start time, and then try very hard to shave off a small bit there.

I understand that it is nice to optimise for speed in whatever hosting provider you're bound to, but it still seems like a bit of a pointless endeavour IMHO.

Unfortunately, there is no way to fix tihs. We depend on `node-fetch`, and the only reasonable way forward is to drop this dependency. This means we also have to drop support for some versions of Node.js. This would be a breaking change, so we cannot do it.

Rest assured that we are going to drop support for old Node versions once we do a 2.0 release, but this is not going to happen too soon. At that point we can get rid of `node-fetch`, which will fix this “accidentally.”
