### ISSUE TITLE
`parse_mode: "HTML"` ignores `localhost` in links

### ISSUE THREAD

**Issue by vkz** [grammyjs/grammY#471]
This will fail to parse and simply reply with text ignoring the link entity:
```javascript
await ctx.reply(
        `<a href="http://localhost:3000/foobar"> link here </a>`,
        { parse_mode: "HTML" }
        );
```
this will parse and inline URL correctly:
```javascript
await ctx.reply(
        `<a href="http://127.0.0.1:3000/foobar"> link here </a>`,
        { parse_mode: "HTML" }
        );
```
Best guess is the parser doesn't know to expect `localhost` as valid hostname. Outlier case of-course but tripped me while developing a bot.

Thank you

**Comment by dcdunkan** [comment]
Hi @vkz, this is the expected behavior of the Bot API.

grammY core doesn't have parsers for anything, especially not for parsing HTML, Markdown or URLs. Formatted or not, the content parsing is done by Telegram Bot API with TDLib's utilities.

It is not that the parser in TDLib doesn't know to expect localhost URLs. It's just that it doesn't care about them and treats them as a _bad_ and invalid domain in test cases.
