### ISSUE TITLE
Not receiving updates for purchased_paid_media

### ISSUE THREAD

**Issue by danielrhodes** [grammyjs/grammY#639]
I'm been trying to get the updates for `purchased_paid_media` and I'm not seeing them in the latest bot API update (Sept 6th) and grammY v1.30.0. I've been using this template https://github.com/bot-base/telegram-bot-template/blob/main/src/main.ts (allowed updates array is blank), so I don't think I am filtering out those updates.

I've tried a few implementations, from using `filter` to `on` to even trying to install middleware to intercept it. But haven't seen anything come through so far.

Is this my error? How can I dive deeper to know what's going on.

Thank you!

**Comment by KnorpelSenf** [comment]
Do you see the updates when you use something like https://telegram.tools?

**Comment by KnorpelSenf** [comment]
> Do you see the updates when you use something like https://telegram.tools/update-explorer which lets you receive the updates in your browser?

**Comment by macchie** [comment]
Same here!

**Comment by KnorpelSenf** [comment]
@macchie can you maybe answer the question then? It is impossible to investigate anything with so little information, and ignoring questions doesn't help 😅

**Comment by macchie** [comment]
> @macchie can you maybe answer the question then? It is impossible to investigate anything with so little information, and ignoring questions doesn't help 😅

Hope it was safe to past my token there  😅
I cannot get any update on paid media, any other update works fine and i see the output.

**Comment by KnorpelSenf** [comment]
Yes and no. We wrote and maintain the tool, and it is free and open-source, so it can be trusted. That being said, it's never a good idea to paste a token into any website, period. So if you are paranoid, just revoke the token and use the new one for your bot.

Anyway, if the updates don't arrive in the tool, then it means that Telegram does not send the update. This confirms that there is no issue with grammY, and there is no issue with your code. Most likely, the update is not being sent because you're missing one of the necessary conditions:

- if the payload was empty, then no update will be sent to the bot2
- if the paid media was sent to a channel, then no update will be sent to the bot
- if the paid media was not sent by the bot itself, then no update will be sent to the bot

Also, it is a new feature, so there might be a very, very slim chance that there is a bug in Telegram somewhere. It makes sense to investigate the three documented conditions above before assuming that.

**Comment by macchie** [comment]
Can confirm that adding the `payload` does the trick.
Thanks for support!

**Comment by KnorpelSenf** [comment]
I'll assume that @danielrhodes had the same problem before going silent. Closing. Feel free to reopen if there's an unrelated problem.
