### ISSUE TITLE
Add an additional data property within ctx.callbackQuery to improve bot designs

### ISSUE THREAD

**Issue by josephedradan** [grammyjs/grammY#648]
Lets say you have an inline keyboard along with its corresponding callbackQuery registering and associated callback function as seen below.

```js
...
const inlineKeyboard = [
    [
        {
            text: "Add 1",
            callback_data: "cb_add_1",
        },
        {
            text: "Add 2",
            callback_data: "cb_add_2",
        },
        ...
    ],
];

...
await ctx.reply("Header", {
    parse_mode: "Markdown",
    reply_markup: {
        inline_keyboard: inlineKeyboard,
    },
});
...

bot.callbackQuery("cb_add_1", cb_add_1);
bot.callbackQuery("cb_add_2", cb_add_2);
...

```
Is it possible to add an additional data property such as "additional_data" within ctx.callbackQuery so that we can reduce the amount of bot.callbackQuery(...) calls we need to make. The ctx.callbackQuery.additional_data property would then be handled within the callback function given to a single bot.callbackQuery(...) call. 

Example:

```js
...
const inlineKeyboard = [
    [
        {
            text: "Add 1",
            callback_data: "cb_add",
            additional_data: "1",
        },
        {
            text: "Add 2",
            callback_data: "cb_add",
            additional_data: "2",
        },
        ...
    ],
];

...
await ctx.reply("Header", {
    parse_mode: "Markdown",
    reply_markup: {
        inline_keyboard: inlineKeyboard,
    },
});
...

bot.callbackQuery("cb_add", cb_add);  // The cb_add function would handle the ctx.callbackQuery.additional_data property
...
```

**Comment by KnorpelSenf** [comment]
This is limited by what Telegram supports. The Bot API doesn't permit an extra field in a button, so there's no way for grammY to support it.

Instead, you can use `cb_add:1` and `cb_add:2` as button data and then rely on
```ts
bot.callbackQuery(/cb_add:(\d+)/, cb_add)
```
to handle all callback queries with a regular expression. The result of the regex will be provided in `ctx.match`.

You can also pass an array of possible values to `bot.callbackQuery` in order to reduce the number of calls to it.
