### ISSUE TITLE
How to access to AWS Lambda context from webhookCallback

### ISSUE THREAD

**Issue by polRk** [grammyjs/grammY#724]
if I use something like this: 

```ts
let bot = new Bot(process.env['TELEGRAM_BOT_TOKEN']!)

bot.on('message:voice', async (ctx) => {
	await ctx.reply('I got your voice message!')
})


let handler: Handler = async function (event, context) {
	let handle = webhookCallback(bot, 'aws-lambda-async')
       
	return handle(event, context) as unknown as IResponse
};
```

I want pass aws lambda context to Bot context, separately for each request.

**Comment by KnorpelSenf** [comment]
There currently is no way to do that. grammY only expects a Telegram update object from the outside and it doesn't have a way to inject other data.

That being said, you could move the definition of your bot to inside the lambda function. That way, you'll have access to the AWS lambda context through the closure.

You might want to pass initial bot info data to the bot so that it doesn't have to reinitialise for every request. This will save a lot of `getMe` calls. 

You might also want to extract your bot definition to a function and then call that function with the AWS lambda context. That way, your handler doesn't grow too much.

**Comment by polRk** [comment]
Not the best solution, but works fine!

```
let iamToken: IAMToken | undefined
// -->> Telegram
let handler: Handler = async function (event, context) {
	iamToken = context.token
	let handle = webhookCallback(bot, 'aws-lambda-async')

	return handle(event, context) as unknown as IResponse
};

```
