### ISSUE TITLE
Cannot find type definition file for 'node-fetch'.

### ISSUE THREAD

**Issue by ptkdev** [grammyjs/grammY#90]
```
> tsc

node_modules/grammy/out/core/client.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node-fetch'.
```

With typescript 4.4 i received this error when i try compile [my project](https://github.com/ptkdev/aboutmeinfo-telegram-bot/tree/nightly)

**Comment by KnorpelSenf** [comment]
You probably want to enable `skipLibCheck` so that your compiler does not need to check grammY's declaration files.

If you do want to typecheck your dependencies, you can `npm install --save-dev @types/node-fetch@2` in order to install the missing declaration files.

**Comment by ptkdev** [comment]
@types/node-fetch:

<img width="1337" alt="Schermata 2021-11-17 alle 23 26 07" src="https://user-images.githubusercontent.com/442844/142292365-ffa813d3-7cbe-4ceb-ade0-7f0fac2c674b.png">

Default is `false` but `"skipLibCheck": true,` work.

<img width="1019" alt="Schermata 2021-11-17 alle 23 26 29" src="https://user-images.githubusercontent.com/442844/142292407-ab827662-5df6-4ff7-b482-e7f44da996f8.png">

**Comment by KnorpelSenf** [comment]
`node-fetch` upgraded to version 3 and dropped support for CJS. As grammY has no plans on forcing people to use ESM, it will keep on relying on `node-fetch@2`. Note that this version will keep on receiving security patches if necessary.

Along with the upgrade to being ESM-only, `node-fetch` started shipping its own type definitions. That is not the case for v2. The package `@types/node-fetch` is deprecated because of this upgrade, but you must still install it when using `node-fetch@2` (which you do when you're using grammY).
